---
# tasks file for aws-nuke | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and extracting {{ awsnuke_app }} {{ awsnuke_version }}
  unarchive:
    src: "{{ awsnuke_dl_url }}"
    dest: "{{ awsnuke_bin_path }}"
    owner: "{{ awsnuke_app_owner }}"
    group: "{{ awsnuke_app_group }}"
    extra_opts:
      - --transform
      - s/{{ awsnuke_app }}\-v{{ awsnuke_version }}\-{{ awsnuke_os }}\-{{ awsnuke_arch }}/{{ awsnuke_app }}/
    remote_src: yes

- name: Debian/Ubuntu Family | Setting up {{ awsnuke_app }} config directory {{ awsnuke_config_dir }}
  file:
    path: "{{ awsnuke_config_dir }}"
    state: directory
    mode: "{{ awsnuke_config_dir_mode }}"
    owner: "{{ awsnuke_config_dir_owner }}"
    group: "{{ awsnuke_config_dir_group }}"

- name: Debian/Ubuntu Family | Setting up {{ awsnuke_app }} config file {{ awsnuke_template_dest }} in {{ awsnuke_config_dir }}
  template:
    src: "{{ awsnuke_template_source }}"
    dest: "{{ awsnuke_config_dir }}/{{ awsnuke_template_dest }}"
    mode: "{{ awsnuke_template_dest_mode }}"
    owner: "{{ awsnuke_template_dest_owner }}"
    group: "{{ awsnuke_template_dest_group }}"
