---
# tasks file for aws-nuke

- name: "Downloading archive for {{ awsnuke_app }} {{ awsnuke_version }} to {{ awsnuke_bin_path }} on Debian based systems"
  get_url:
    url: "{{ awsnuke_dl_url }}"
    dest: "{{ awsnuke_bin_path }}/{{ awsnuke_app }}"
    mode: "{{ awsnuke_file_mode }}"

- name: "Setting up {{ awsnuke_app }} config directory on Debian based systems."
  file:
    path: "{{ awsnuke_config_dir }}"
    state: directory
    mode: "{{ awsnuke_config_dir_mode }}"
    owner: "{{ awsnuke_config_dir_owner }}"
    group: "{{ awsnuke_config_dir_group }}"

- name: "Setting up {{ awsnuke_app }} config file {{ awsnuke_template_dest }} in {{ awsnuke_config_dir }} on Debian based systems."
  template:
    src: "{{ awsnuke_template_source }}"
    dest: "{{ awsnuke_config_dir }}/{{ awsnuke_template_dest }}"
    mode: "{{ awsnuke_template_dest_mode }}"
    owner: "{{ awsnuke_template_dest_owner }}"
    group: "{{ awsnuke_template_dest_group }}"
